### PR TITLE
Fix deleting and nuking - Using zalmoxis fix

### PR DESCRIPTION
**Pull request by meeoh**
Appends the proper xsrf token

Tested and working on mac and raspberry pi (raspbian)

### CODE REVIEW

**Comment by meeoh** [comment]
@ArthurG Can we get this through? Nuking/deleting does not work without it

**Comment by AminDhouib** [comment]
I can confirm that this fix solves the deletion issue. A merge should indeed be considered.

**Comment by meeoh** [comment]
@ArthurG Can we get this merged?

**Comment by meeoh** [comment]
Bumping this again @ArthurG

**Pull request merged**
