### PR TITLE
Changed title character minimum from 10 to 8 and Applied Strip() to title.

### PR DESCRIPTION
**Pull request by jordanmehravar**

### CODE REVIEW

**Comment by jackm** [comment]
Did the Kijiji site change the minimum character requirement in ad titles from 10 down to 8? Was this when they did their big new ad posting interface change?

**Comment by ArthurG** [comment]
From my testing, it seems like 8 characters titles work fine. Unless you object, @jackm  I'll approve this request

**Comment by jordanmehravar** [comment]
I discovered this change by manually creating an ad. Perhaps the character limit depends on the category you post in. For now, this limit seems to work.

**Comment by jackm** [comment]
Yes it would appear the new minimum length is 10 characters. The new ad posting UI even shows a counter counting down from 8 when entering in an ad title.

**Comment by ArthurG** [comment]
@jack did you mean the new minimum length is 10 letters?

**Comment by jackm** [comment]
Typo, I meant the new minimum length is indeed 8 characters, no longer 10.

**Pull request closed without merging**
