### PR TITLE
 Change the way photos and .inf files are loaded

### PR DESCRIPTION
**Pull request by ArthurG**
- .inf files are now called .kj_post (to minimize confusion with backward compatibility)
- .kj_post files now use YAML, all past .inf files are now incompatible
- Allow storing login info in kj_post files
- Images are stored relative to the .kj_post location, to minimize confusion for new users
- Remove repost_folder and folder commands, since kj_post files make them useless
- Minor code cleanup

### CODE REVIEW

**Comment by ArthurG** [comment]
I'm open to constructive feedback on this PR

**Comment by cerberii** [comment]
suggestion: also allow using login.inf format to store login credentials in directory where .kj_pst file is or higher directory. ex:
so reverse-recursivly search for login.inf file 

so then credentials can be specified in yaml item1.kj_post or as file
```
variables:
  login-info: ~/credentials/login.inf
```

or

```
variables:
  login-info: login 
  password: pass
```

**Comment by jackm** [comment]
I've checked out this branch and did a quick test by generating a new .kj_post file using the "build_ad" argument and then posting a new ad with it.

Works great from what I can see, and I have to say that I do prefer using YAML instead of the not-so-standard _var=value_ format as it looks much cleaner. I also tend to manually edit my ad files and using YAML helps in that regard also.

As @cerberii has said, it would be good to have a separate login credentials file as an option too.

**Comment by jackm** [comment]
One other suggestion that I'd like to make is to use _.yaml_ as a file extension instead of _.kj_post_ just to help show what the file format really is. It might also help when opening the files in other programs as a hint to let them know what the syntax should be.

@ArthurG thoughts on this?

**Comment by jackm** [comment]
Another bonus of using YAML - it lets you do great things like multiline text and easier to write lists! Very powerful markup language indeed.

Snippit of an example ad details file:
```
postAdForm.title: This is the ad title
postAdForm.description: |-
  This is the ad description
  Line 2
  
  Line 4
  
  
  Line 7
  No trailing newline after this line
image_paths:
  - 1.jpg
  - 2.jpg
```

**Comment by jackm** [comment]
I've created a small python script that can convert the old inf ad format to the new yaml ad format. It can be found on the [`new-file-format2`](https://github.com/jackm/Kijiji-Repost-Headless/tree/new-file-format2) branch in my repo.

Direct link: [inf2yaml.py](https://github.com/jackm/Kijiji-Repost-Headless/blob/new-file-format2/kijiji_repost_headless/inf2yaml.py)

💥 Note that this script is not likely to be perfect. I only accounted for the "common" ad types so ads meant for the "other" category or ones in the automotive categories probably have more fields that I haven't accounted for. Please double check the converted yaml files after to make sure that they're correct.

**Comment by jackm** [comment]
I've created a new PR GH-73 for this branch (new-file-format2) with improvements to be added before this PR is merged into the master branch.

**Pull request merged**
