### PR TITLE
Revive extension by supporting repost all working command 

### PR DESCRIPTION
**Pull request by ArthurG**
This PR migrates the Kijiji API to the mingle.kijiji.ca api (thanks to rybodiddly/Kijiji-Reposter/ for the inspiration!)

To easily test this new feature, I also add a `repost_all` command to the CLI tool.

### CODE REVIEW

**Comment by meeoh** [comment]
@ArthurG So does this PR break the logout, delete_ad_using_title, upload_image methods?

`upload_image` and `delete_ad_using_title` is kinda important!

**Comment by ArthurG** [comment]
From the comments on the recent issues, I thought people were already having issues - so I'm going to start gradually refactoring the extension using the mobile Kijiji API instead of the web api. 

Those two are not implemented yet, do you have a use case why they are needed? I thought the `repost_all` command should be what most users are looking for anyway, so I implemented it first.

**Comment by meeoh** [comment]
> From the comments on the recent issues, I thought people were already having issues - so I'm going to start gradually refactoring the extension using the mobile Kijiji API instead of the web api.
> 
> Those two are not implemented yet, do you have a use case why they are needed? I thought the `repost_all` command should be what most users are looking for anyway, so I implemented it first.

That makes sense!

Yeah repost_all is all I need tbh, I was just imagining what other people probably find useful. Also since repost_all deletes ads, I guess the `delete_ad_using_title` could be implemented in a similar way?

Also the upload_image part I think is probably blocking for most people, since reposting wont upload the images again right, so they'll be lost?

**Comment by ArthurG** [comment]
The images from the old ad is copied over, nothing should be lost 

delete_ad_using_title could be easily reimplemented. But I'll leave that as a task for another contributor unless someone can convince me why it's super useful.

**Comment by meeoh** [comment]
> The images from the old ad is copied over, nothing should be lost 
> 
> 
> 
> delete_ad_using_title could be easily reimplemented. But I'll leave that as a task for another contributor unless someone can convince me why it's super useful.
> 
> 

Oh interesting. I'm guessing it's just using the same image urls that existed in the ad?

**Comment by oxgitter** [comment]
Seems like post and repost no longer work. Is this an intended effect of the update?

**Comment by meeoh** [comment]
> Seems like post and repost no longer work. Is this an intended effect of the update?

I think he mentioned that repost should still work with this. Or maybe it's a new repost function. 

Either way, if you want the old functionality you can just check out the commit before this

**Comment by ArthurG** [comment]
Yes, post and repost no longer work. Would you be interested in creating a PR to revive that functionality? @oxgitter

**Comment by Rings4** [comment]
> Yes, post and repost no longer work. Would you be interested in creating a PR to revive that functionality? @oxgitter

I'd like for post and repost to work. They're literally the only things I've ever used on this. I post an ad, then I repost it daily. I don't want to repost everything at once because for ads that I have customers responding to, reposting it makes them think I sold it.

**Comment by meeoh** [comment]
> > Yes, post and repost no longer work. Would you be interested in creating a PR to revive that functionality? @oxgitter
> 
> I'd like for post and repost to work. They're literally the only things I've ever used on this. I post an ad, then I repost it daily. I don't want to repost everything at once because for ads that I have customers responding to, reposting it makes them think I sold it.

If you really want those back just checkout `ad5db90499da3b3f13d4a6817a3ddd8779d31a9e` and use it from there, it should be fine. I just forked it at that state and thats what I use!

**Comment by Rings4** [comment]
> > > Yes, post and repost no longer work. Would you be interested in creating a PR to revive that functionality? @oxgitter
> > 
> > 
> > I'd like for post and repost to work. They're literally the only things I've ever used on this. I post an ad, then I repost it daily. I don't want to repost everything at once because for ads that I have customers responding to, reposting it makes them think I sold it.
> 
> If you really want those back just checkout `ad5db90499da3b3f13d4a6817a3ddd8779d31a9e` and use it from there, it should be fine. I just forked it at that state and thats what I use!

Omg, thank you very much! I've been getting tired of having to manually delete my ads before reposting them, you're a life saver!

**Pull request merged**
