### PR TITLE
updated ua and random agent switcher

### PR DESCRIPTION
**Pull request by getsec**
Updated the Kijiji API to use a random user agent. Chosen from either MacOSX/Windows Chrome/FF. I've created an ad in the buy and sell and I haven't had an issue.

❤️

### CODE REVIEW

**Comment by ArthurG** [comment]
Nice! Thanks for the quick change! I think the issue with #173 is related to the `generate_post_file.py` file. Can you also make the changes over in that file as well?

**Comment by getsec** [comment]
> Nice! Thanks for the quick change! I think the issue with #173 is related to the `generate_post_file.py` file. Can you also make the changes over in that file as well?

whoops. Totes, on it.

**Comment by getsec** [comment]
@ArthurG Should be good now.

**Comment by ArthurG** [comment]
Thank you for your contribution!!

**Comment by getsec** [comment]
I hope to contribute more when needed :)

**Pull request merged**
