### PR TITLE
Make ad delection/checking a bit smarter

### PR DESCRIPTION
**Pull request by shameelabd**
I have multiple ads with the same name under different categories, so everything was being deleted at once. This PR makes it so that when deleting/checking ad existence, it also respects the ads category

### CODE REVIEW

**Comment by prgrm** [comment]
This is the kind of abuse that makes Kijiji more cluttered and pushes them to implement countermeasures against this project.

**Comment by shameelabd** [comment]
> This is the kind of abuse that makes Kijiji more cluttered and pushes them to implement countermeasures against this project.

Having multiple ads under multiple catgories is abuse? Im renting a home and it falls under short-term rental, long-term rental, and roomate rental. Is this not allowed?

**Comment by shameelabd** [comment]
Also not sure why you're on this account and not ArthurG, must of been an accident? 😛

**Comment by ArthurG** [comment]
This seems like a very reasonable change. Thanks for the contribution!

**Pull request merged**
