### PR TITLE
update kijiji api with new kijiji address for fixing login failure

### PR DESCRIPTION
**Pull request by astrion**
To fix the login failure discussed here: https://github.com/ArthurG/Kijiji-Repost-Headless/issues/217
Credit: @JohnBakery  https://github.com/JohnBakery

### CODE REVIEW

**Comment by Aluui** [comment]
I also verified that this works

**Review by shameelabd — APPROVED** [review]

**Comment by Schamp1** [comment]
bump, please merge this

**Comment by meeoh** [comment]
@Schamp1 its eems like the maintainer isnt active anymore, my recommendation is to fork this pr and run it like that, thats what im doing 🤷

**Comment by Connor2hd** [comment]
Hey guys if this isn't working for you maybe check out this repo: https://github.com/rybodiddly/Kijiji-Reposter

It's had more recent commits and has been working quite well for me.  Similar idea but with a UI.

**Comment by meeoh** [comment]
> Hey guys if this isn't working for you maybe check out this repo: https://github.com/rybodiddly/Kijiji-Reposter
> 
> 
> 
> It's had more recent commits and has been working quite well for me.  Similar idea but with a UI.

Oh that's awesome! The appeal of this repo for me is that it's headless, but it seems like that one uses a similar but updated Kijiji api wrapper, so maybe some scripts can be written that interact with it!

Thanks

**Pull request merged**
